### ISSUE TITLE
Adding jsdoc to the declarations

### ISSUE THREAD

**Issue by miltoncandelero** [scambier/tic80-typescript#6]
I am adding the corresponding jsdoc to the declarations in tic.d.ts so we have the same documentation as in the wiki inside our editor (vscode in my case).

I will PR soon. I hope you are still alive <3

**Comment by scambier** [comment]
Hello! I'm still very well alive, just working on private projects, thanks for your concern :D

I just took a look at TIC docs, and I see that some functions have been added since my last update a year ago. Maybe could you add their declarations to the `tic.d.ts` too, please? I'm quite happy to see that this project is still being used!

**Comment by scambier** [comment]
Merged and published on npm, thanks again.
