### ISSUE TITLE
Project structure

### ISSUE THREAD

**Issue by Chris-Mingay** [scambier/tic80-typescript#9]
Hi there, first off thanks for this project it sounds like exactly what I'm after. 

Not an issue with your work, more my own inexperience with typescript but I've fallen at the first hurdle, I'm not sure how I go about referencing classes in different files. Are you able to provide any pointers?

Instinctively I wanted to do something like

**./src/Thing.ts**
```ts
export class Thing {

    name: string;

    constructor(_name: string){
        this.name = _name;
    }

}
```

**main.ts**
```ts
// title:  game title
// author: game developer
// desc:   short description
// script: js

import { Thing } from './src/Thing';

let t = 0
let x = 96
let y = 24

let items: Thing[] = [
  new Thing("Chris"),
  new Thing("Bob"),
  new Thing("Freddie")
]

function TIC() {
  if (btn(0)) y--
  if (btn(1)) y++
  if (btn(2)) x--
  if (btn(3)) x++
  cls(13)
  spr(1 + (((t % 60) / 30) | 0) * 2, x, y, 14, 3, 0, 0, 2, 2)
  print("HELLO WORLD 2!", 84, 84)

  let tY = 0;
  items.forEach(item => {
    print(item.name, 0, tY);
    tY+=10;
  })

  t++
}
```

When I try `tsc80 run` I get

`"src/Thing.ts(1,14): error TS6131: Cannot compile modules using option 'outFile' unless the '--module' flag is 'amd' or 'system'.\r\n",`

If I set the module to `amd` in tsconfig.json the application compiles but from within TIC80 I get

![image](https://user-images.githubusercontent.com/71371350/168573409-7fa8be65-e18e-49f9-b999-f2159a4d3642.png)

If I set the module to `system`  in tsconfig.json the application compiles but from within TIC80 I get

![image](https://user-images.githubusercontent.com/71371350/168573640-79ec47d6-7895-40ad-8ce2-f0a40d4aaa73.png)

Thanks

**Comment by scambier** [comment]
**2024 edit**: TSC-80 2.0 now fully supports ESM with `import` and `export`. Triple-slash references and namespaces are not needed anymore

---

Hello Chris :) Yes the project structure can look a bit weird, compared to more traditional TypeScript projects, mainly due to a lack of support for modules. I've tried to explain a bit how it works [here](https://github.com/scambier/tic80-typescript#code-organization--limitations). The most important thing to understand is that **_everything_ declared at file level is global**. So, your example should be written like this:

**./src/Thing.ts**
```ts
class Thing {

    name: string;

    constructor(_name: string){
        this.name = _name;
    }

}
```

**./main.ts**
```ts
// title:  game title
// author: game developer
// desc:   short description
// script: js

// optionally:
/// <reference path="./src/Thing.ts" />

let t = 0
let x = 96
let y = 24

let items: Thing[] = [
  new Thing("Chris"),
  new Thing("Bob"),
  new Thing("Freddie")
]

function TIC() {
  if (btn(0)) y--
  if (btn(1)) y++
  if (btn(2)) x--
  if (btn(3)) x++
  cls(13)
  spr(1 + (((t % 60) / 30) | 0) * 2, x, y, 14, 3, 0, 0, 2, 2)
  print("HELLO WORLD 2!", 84, 84)

  let tY = 0;
  items.forEach(item => {
    print(item.name, 0, tY);
    tY+=10;
  })

  t++
}
```

What the tool basically does is take all your .ts files, and compile them "as-is", into a single .js file (literally the `tsc` command). The triple-slash `<reference>` directives are not required since everything is global, but they make sure that files are included in the right order if they depend on each other.

You can also use namespaces for a better encapsulation:
```ts
namespace Foo {
    let count = 0
    export function bar() {
        return ++count
    }
}

Foo.bar()
```

**Comment by Chris-Mingay** [comment]
That's amazing thank you so much, sorry I did see your bit about `<reference>` but wasn't sure how it translated into what I was expecting/understood.

Being able to use typescript is going to make my life so much easier, it felt like my lua based project was slowly getting out of hand.

I guess that because the source I am writing is just plain old typescript I'll be able to write unit tests and the like too?

Thanks once again

**Comment by scambier** [comment]
You're welcome :D

Unit tests should work, you just might have to tweak the tsconfig and/or write another one in your tests directory to cleanly separate them from source files 👍 
Don't hesitate to open another issue if UT don't work, and I'll take a better look.
